image: python:3.8

stages:
  - lint
  - test
  - deploy

lint-job:
  stage: lint
  script:
    - python -m pip install wemake-python-styleguide==0.16.1
    - flake8 src/
  tags: ['cvr-nov22']

test-job:
  stage: test
  script:
    - python -m pip install pytest==7.1.2
    - PYTHONPATH=. pytest tests -p no:warnings
  tags: ['cvr-nov22']
